name: Deploy .NET to EBS
on:
  push:
    branches:
    - main
    - development
jobs:
  build_deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
    - name: Publish
      run: dotnet publish -c Release -o ./app/ src/Hyme.API/Hyme.API.csproj
    - name: Generate deployment package
      run: cd src/Hyme.API/Hyme.API.csproj; zip -r ../deploy.zip . -x '*.git*'; cd ..
    - name: Upload .NET to artifact
      uses: actions/upload-artifact@v3
      with:
        name: dotnet-zip
        path: deploy.zip
    - name: Setup EB CLI
      run: |
        python --version
        pip --version
        pip install awsebcli --upgrade --user
        eb --version
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2 # More information on this action can be found below in the 'AWS Credentials' section
      with:
         aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         application_name: HymeAPI
         environment_name: testHYME
         version_label: ${{ github.run_id }}
         region: ${{ secrets.AWS_REGION }}
    - name: Deploy to EB
      run: eb deploy dotnet-env-dev --staged
